package fiber_adapter

import (
	"fmt"
	"strings"

	"github.com/abdullahPrasetio/go-wapbolt/wapbolt"
	"github.com/gofiber/fiber/v2"
)

// ParseRoutes extracts all routes from a Fiber app and adds them to a Wapbolt collection
func ParseRoutes(app *fiber.App, collection *wapbolt.Collection, baseUrl string) {
	routes := app.GetRoutes()

	findFolder := func(name string) *wapbolt.Item {
		for i := range collection.Item {
			if collection.Item[i].Name == name && collection.Item[i].Request == nil {
				return &collection.Item[i]
			}
		}
		return collection.AddFolder(name)
	}

	for _, route := range routes {
		if route.Method == "USE" || route.Method == "HEAD" || route.Method == "OPTIONS" {
			continue
		}

		path := route.Path
		segments := strings.Split(strings.Trim(path, "/"), "/")
		
		folderName := "General"
		if len(segments) > 0 && segments[0] != "" {
			folderName = strings.Title(segments[0])
		}

		folder := findFolder(folderName)

		normalizedPath := strings.ReplaceAll(path, ":", "")

		reqItem := wapbolt.Item{
			Name: fmt.Sprintf("%s [%s]", path, route.Method),
			Request: &wapbolt.Request{
				Method: route.Method,
				URL:    fmt.Sprintf("%s%s", baseUrl, normalizedPath),
				Header: []wapbolt.HeaderField{
					{Key: "Accept", Value: "application/json"},
				},
			},
		}

		if route.Method == "POST" || route.Method == "PUT" || route.Method == "PATCH" {
			reqItem.Request.Body = &wapbolt.Body{
				Mode: "raw",
				Raw:  "{\n  \n}",
			}
			reqItem.Request.Header = append(reqItem.Request.Header, wapbolt.HeaderField{
				Key:   "Content-Type",
				Value: "application/json",
			})
		}

		cleanPath := strings.TrimSuffix(path, "/")
		meta, ok := wapbolt.GetMetadata(route.Method, path)
		if !ok {
			meta, ok = wapbolt.GetMetadata(route.Method, cleanPath)
		}

		if ok {
			if meta.Description != "" {
				reqItem.Request.Description = meta.Description
			}
			if meta.FieldValidations != nil {
				reqItem.Request.FieldValidations = meta.FieldValidations
			}
			if len(meta.Examples) > 0 {
				reqItem.Request.Responses = meta.Examples
			}

			if reqItem.Request.Body != nil && (reqItem.Request.Body.Raw == "" || reqItem.Request.Body.Raw == "{\n  \n}") {
				if bodyMeta, ok := meta.FieldValidations["body"].(map[string]interface{}); ok {
					reqItem.Request.Body.Raw = wapbolt.GenerateSampleBody(bodyMeta)
				}
			}
		}

		folder.AddRequest(reqItem)
	}
}

// Register automatically adds a route to your Fiber app that serves the Wapbolt collection
func Register(app *fiber.App, endpoint string, baseUrl string) {
	app.Get(endpoint, func(c *fiber.Ctx) error {
		wapbolt.AutoScan(".")
		col := wapbolt.NewCollection("API Collection", "Auto-generated by go-wapbolt")
		ParseRoutes(app, col, baseUrl)
		jsonBytes, err := col.ToJSON()
		if err != nil {
			return c.Status(500).SendString(err.Error())
		}
		c.Set("Content-Type", "application/json")
		c.Set("Content-Disposition", "attachment; filename=wapbolt-collection.json")
		return c.Send(jsonBytes)
	})
}
