package gin_adapter

import (
	"fmt"
	"regexp"
	"strings"
	"unicode"

	"github.com/abdullahPrasetio/go-wapbolt/wapbolt"
	"github.com/gin-gonic/gin"
)

var paramRe = regexp.MustCompile(`:([a-zA-Z_][a-zA-Z0-9_]*)`)

func titleCase(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

// ParseRoutes extracts all routes from a Gin engine and adds them to a Wapbolt collection.
// exportEndpoint: path of the export route to exclude from the collection (e.g. "/export-docs").
func ParseRoutes(engine *gin.Engine, collection *wapbolt.Collection, baseUrl string, exportEndpoint ...string) {
	routes := engine.Routes()

	skipPath := ""
	if len(exportEndpoint) > 0 {
		skipPath = exportEndpoint[0]
	}

	findFolder := func(name string) *wapbolt.Item {
		for i := range collection.Item {
			if collection.Item[i].Name == name && collection.Item[i].Request == nil {
				return &collection.Item[i]
			}
		}
		return collection.AddFolder(name)
	}

	for _, route := range routes {
		if route.Method == "HEAD" || route.Method == "OPTIONS" {
			continue
		}
		if skipPath != "" && route.Path == skipPath {
			continue
		}

		path := route.Path
		segments := strings.Split(strings.Trim(path, "/"), "/")

		folderName := "General"
		if len(segments) > 0 && segments[0] != "" {
			folderName = titleCase(segments[0])
		}

		folder := findFolder(folderName)

		// Convert :param → {{param}} (Postman/Wapbolt convention)
		normalizedPath := paramRe.ReplaceAllString(path, "{{$1}}")

		reqItem := wapbolt.Item{
			Name: fmt.Sprintf("%s [%s]", path, route.Method),
			Request: &wapbolt.Request{
				Method: route.Method,
				URL:    fmt.Sprintf("%s%s", baseUrl, normalizedPath),
				Header: []wapbolt.HeaderField{
					{Key: "Accept", Value: "application/json"},
				},
			},
		}

		// Add default body placeholder
		if route.Method == "POST" || route.Method == "PUT" || route.Method == "PATCH" {
			reqItem.Request.Body = &wapbolt.Body{
				Mode: "raw",
				Raw:  "{\n  \n}",
			}
			reqItem.Request.Header = append(reqItem.Request.Header, wapbolt.HeaderField{
				Key:   "Content-Type",
				Value: "application/json",
			})
		}

		// Check for registered metadata
		// Try exact match first, then without trailing slash
		cleanPath := strings.TrimSuffix(path, "/")
		meta, ok := wapbolt.GetMetadata(route.Method, path)
		if !ok {
			meta, ok = wapbolt.GetMetadata(route.Method, cleanPath)
		}

		if ok {
			if meta.Description != "" {
				reqItem.Request.Description = meta.Description
			}
			if meta.FieldValidations != nil {
				reqItem.Request.FieldValidations = meta.FieldValidations
			}
			if len(meta.Examples) > 0 {
				reqItem.Request.Responses = meta.Examples
			}

			// AUTO GENERATE SAMPLE BODY from validations if raw is empty
			if reqItem.Request.Body != nil && (reqItem.Request.Body.Raw == "" || reqItem.Request.Body.Raw == "{\n  \n}") {
				if bodyMeta, ok := meta.FieldValidations["body"].(map[string]interface{}); ok {
					reqItem.Request.Body.Raw = wapbolt.GenerateSampleBody(bodyMeta)
				}
			}
		}

		folder.AddRequest(reqItem)
	}
}

// Register automatically adds a route to your Gin app that serves the Wapbolt collection.
// The export endpoint itself is excluded from the generated collection.
func Register(r *gin.Engine, endpoint string, baseUrl string) {
	r.GET(endpoint, func(c *gin.Context) {
		// 1. Auto Scan
		wapbolt.AutoScan(".")

		// 2. Build Collection (exclude the export endpoint itself)
		col := wapbolt.NewCollection("API Collection", "Auto-generated by go-wapbolt")
		ParseRoutes(r, col, baseUrl, endpoint)

		// 3. Output as JSON File
		jsonBytes, err := col.ToJSON()
		if err != nil {
			c.String(500, err.Error())
			return
		}

		c.Header("Content-Type", "application/json")
		c.Header("Content-Disposition", "attachment; filename=wapbolt-collection.json")
		c.Data(200, "application/json", jsonBytes)
	})
}
